### ISSUE TITLE
资源插件查询失败报错

### ISSUE THREAD

**Issue by hypergraphUniverse** [py-plugin-apps/where_resource#1]
版本：云崽3.0.0 + py 1.2.0
> 曾经有安装过更早版本的py插件，然后进行了更新，显示的py插件管理是v1.0.0，不知道有没有影响

部署：Debian + Docker + 国内服务器部署
现象：无反应，记录报错

日志：
yunzai-bot    | [YzBot][05:51:49.330][MARK] [where_resource][where_help][私聊][111-2(1599010773)] #地图资源查询教程
yunzai-bot    | [YzBot][05:51:49.344][MARK] [where_resource][where_help] #地图资源查询教程 处理完成 12ms
yunzai-bot    | Error: 13 INTERNAL: Traceback (most recent call last):
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 186, in connect_tcp
yunzai-bot    |     addr_obj = ip_address(remote_host)
yunzai-bot    |   File "/usr/lib/python3.9/ipaddress.py", line 53, in ip_address
yunzai-bot    |     raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
yunzai-bot    | ValueError: 'uploadstatic.mihoyo.com' does not appear to be an IPv4 or IPv6 address
yunzai-bot    |
yunzai-bot    | During handling of the above exception, another exception occurred:
yunzai-bot    |
yunzai-bot    | Traceback (most recent call last):
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 109, in connect_tcp
yunzai-bot    |     stream: anyio.abc.ByteStream = await anyio.connect_tcp(
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 189, in connect_tcp
yunzai-bot    |     gai_res = await getaddrinfo(
yunzai-bot    | asyncio.exceptions.CancelledError
yunzai-bot    |
yunzai-bot    | During handling of the above exception, another exception occurred:
yunzai-bot    |
yunzai-bot    | Traceback (most recent call last):
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
yunzai-bot    |     yield
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 109, in connect_tcp
yunzai-bot    |     stream: anyio.abc.ByteStream = await anyio.connect_tcp(
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
yunzai-bot    |     raise TimeoutError
yunzai-bot    | TimeoutError
yunzai-bot    |
yunzai-bot    | During handling of the above exception, another exception occurred:
yunzai-bot    |
yunzai-bot    | Traceback (most recent call last):
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
yunzai-bot    |     yield
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
yunzai-bot    |     resp = await self._pool.handle_async_request(req)
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
yunzai-bot    |     raise exc
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
yunzai-bot    |     response = await connection.handle_async_request(request)
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
yunzai-bot    |     raise exc
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
yunzai-bot    |     stream = await self._connect(request)
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpcore/_async/connection.py", line 111, in _connect
yunzai-bot    |     stream = await self._network_backend.connect_tcp(**kwargs)
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpcore/backends/auto.py", line 29, in connect_tcp
yunzai-bot    |     return await self._backend.connect_tcp(
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 109, in connect_tcp
yunzai-bot    |     stream: anyio.abc.ByteStream = await anyio.connect_tcp(
yunzai-bot    |   File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
yunzai-bot    |     self.gen.throw(type, value, traceback)
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
yunzai-bot    |     raise to_exc(exc)
yunzai-bot    | httpcore.ConnectTimeout
yunzai-bot    |
yunzai-bot    | The above exception was the direct cause of the following exception:
yunzai-bot    |
yunzai-bot    | Traceback (most recent call last):
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/apps/where_resource/py/util.py", line 155, in create
yunzai-bot    |     await downloader.init()
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/apps/where_resource/py/util.py", line 49, in init
yunzai-bot    |     await self.get_icon()
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/apps/where_resource/py/util.py", line 93, in get_icon
yunzai-bot    |     icon = Image.open(BytesIO(i.result().content))
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/apps/where_resource/py/util.py", line 44, in get
yunzai-bot    |     res = await self.client.get(url, follow_redirects=True)
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1751, in get
yunzai-bot    |     return await self.request(
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1527, in request
yunzai-bot    |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1614, in send
yunzai-bot    |     response = await self._send_handling_auth(
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
yunzai-bot    |     response = await self._send_handling_redirects(
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
yunzai-bot    |     response = await self._send_single_request(request)
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1716, in _send_single_request
yunzai-bot    |     response = await transport.handle_async_request(request)
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
yunzai-bot    |     resp = await self._pool.handle_async_request(req)
yunzai-bot    |   File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
yunzai-bot    |     self.gen.throw(type, value, traceback)
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
yunzai-bot    |     raise mapped_exc(message) from exc
yunzai-bot    | httpx.ConnectTimeout
yunzai-bot    |
yunzai-bot    | During handling of the above exception, another exception occurred:
yunzai-bot    |
yunzai-bot    | Traceback (most recent call last):
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/core/server/server.py", line 20, in FrameToFrame
yunzai-bot    |     return await handler(request)
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/apps/where_resource/py/__init__.py", line 11, in where_resource_help
yunzai-bot    |     return Response(json.dumps(await ResourceMap.help()))
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/apps/where_resource/py/util.py", line 342, in help
yunzai-bot    |     cls.downloader = await Downloader.create()
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/apps/where_resource/py/util.py", line 156, in create
yunzai-bot    |     return downloader
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1997, in __aexit__
yunzai-bot    |     await self._transport.__aexit__(exc_type, exc_value, traceback)
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 332, in __aexit__
yunzai-bot    |     await self._pool.__aexit__(exc_type, exc_value, traceback)
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 326, in __aexit__
yunzai-bot    |     await self.aclose()
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 312, in aclose
yunzai-bot    |     raise RuntimeError(
yunzai-bot    | RuntimeError: The connection pool was closed while 117 HTTP requests/responses were still in-flight.
yunzai-bot    |
yunzai-bot    |     at callErrorFromStatus (/app/Yunzai-Bot/node_modules/.pnpm/@grpc+grpc-js@1.8.0/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
yunzai-bot    |     at Object.onReceiveStatus (/app/Yunzai-Bot/node_modules/.pnpm/@grpc+grpc-js@1.8.0/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
yunzai-bot    |     at Object.onReceiveStatus (/app/Yunzai-Bot/node_modules/.pnpm/@grpc+grpc-js@1.8.0/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
yunzai-bot    |     at Object.onReceiveStatus (/app/Yunzai-Bot/node_modules/.pnpm/@grpc+grpc-js@1.8.0/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
yunzai-bot    |     at /app/Yunzai-Bot/node_modules/.pnpm/@grpc+grpc-js@1.8.0/node_modules/@grpc/grpc-js/build/src/resolving-call.js:93:78
yunzai-bot    |     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
yunzai-bot    | for call at
yunzai-bot    |     at ServiceClientImpl.makeUnaryRequest (/app/Yunzai-Bot/node_modules/.pnpm/@grpc+grpc-js@1.8.0/node_modules/@grpc/grpc-js/build/src/client.js:160:34)
yunzai-bot    |     at ServiceClientImpl.<anonymous> (/app/Yunzai-Bot/node_modules/.pnpm/@grpc+grpc-js@1.8.0/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
yunzai-bot    |     at FrameToFrame (file:///app/Yunzai-Bot/plugins/py-plugin/core/client/client.js:60:47)
yunzai-bot    |     at Object.where_help [as handler] (file:///app/Yunzai-Bot/plugins/py-plugin/apps/where_resource/js/index.js:42:3)
yunzai-bot    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
yunzai-bot    |     at async Proxy.<computed> [as where_help] (file:///app/Yunzai-Bot/plugins/py-plugin/index.js:134:12)
yunzai-bot    |     at async PluginsLoader.deal (file:///app/Yunzai-Bot/lib/plugins/loader.js:251:52)

**Comment by hypergraphUniverse** [comment]
看了下，好像现在新的py插件结构大改了啊……这个插件是不是不能用了

**Comment by hypergraphUniverse** [comment]
现在xiaoyao插件已经有类似的功能了。就不打扰了。
